[package]
name = "wasmer/wasix-axum-example"
version = "0.1.3"
description = "Package to showcase a news scraper on wasmer edge"
wasmer-extra-flags = "--net --enable-threads --enable-bulk-memory"

[dependencies]

[[module]]
name = "wasix-axum"
source = "target/wasm32-wasmer-wasi/release/wasix-axum.wasm"

[[command]]
name = "wasix-axum"
module = "wasix-axum"
runner = "wasi@unstable_"
